kind: "Template"
apiVersion: "v1"
metadata:
  name: "ops"
  openshift.io/display-name: "ops"
  tags: "ops"
parameters:
- description: По умолчанию - 'vg'.
  name: NAMESPACE
  value: vg
objects:
- apiVersion: v1
  kind: Service
  metadata:
    name: jenkins
  spec:
    ports:
    - port: 8080
      targetPort: 8080
    selector:
      deploymentconfig: jenkins
- apiVersion: v1
  kind: Route
  metadata:
    name: jenkins
  spec:
    to:
      kind: Service
      name: jenkins
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: jenkins
  spec:
    dockerImageRepository: docker.io/gurv/jenkins
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: jenkins
  spec:
    replicas: 1
    selector:
      deploymentconfig: jenkins
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          deploymentconfig: jenkins
      spec:
        containers:
        - image: gurv/jenkins:latest
          name: jenkins
          ports:
          - containerPort: 8080
            protocol: TCP
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - jenkins
        from:
          kind: ImageStreamTag
          name: jenkins:latest
      type: ImageChange
