version: '3.4'

services:
  portainer:
    image: vg/portainer:latest
    ports:
      - 9000:9000 # tcp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data

#FIXME
#  docker-cli:
#    image: vg/docker-cli:latest
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock
#    ports:
#      - 23:22 # ssh

#FIXME
#  docker-registry:
#    image: vg/docker-registry:latest

  jenkins:
    image: vg/jenkins:latest
    ports:
      - '8085:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_home:/var/jenkins_home

  nexus:
    image: vg/nexus:latest
    ports:
      - '8086:8081'
    volumes:
      - nexus:/nexus-data

  sonarqube:
    image: vg/sonarqube:latest
    ports:
      - '8087:9000' # http
    networks:
      - sonarqube_net
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled_plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube_db:
    image: vg/postgres:latest
    hostname: sonarqube_db
    networks:
      - sonarqube_net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarqube_db_data:/var/lib/postgresql/data

networks:
  sonarqube_net:

volumes:
  portainer:
  nexus:
  sonarqube_db_data:
  jenkins_home:
  sonarqube_bundled_plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions: