version: "3.4"

volumes:
  prometheus: {}
#  prometheus:
#    source: ./.dev/prometheus_data
  grafana: {}

services:
  grafana:
    image: vg/grafana:latest
    hostname: grafana
    networks:
      - proxy_net
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  prometheus:
    image: vg/prometheus:latest
    hostname: prometheus
    networks:
    - proxy_net
    ports:
      - "9090:9090"
    volumes:
      - prometheus:/prometheus
#      - ./.dev/prometheus_data:/prometheus
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          memory: 2048M
        reservations:
          memory: 128M