version: '3.4'

volumes:
    portainer: {}

services:
  portainer:
    image: vg/portainer:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
    ports:
      - 9000:9000 # tcp

  docker-cli:
    image: vg/docker-cli:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 23:22 # ssh

  docker-registry:
    image: vg/docker-registry:latest

  jenkins:
    image: vg/jenkins:latest
    ports:
    - '8085:8080'