version: '3.4'

services:
  zookeeper:
    image: vg/zookeeper:latest
    ports:
      - 2181:2181 # clientPort
      - 2888:2888 # peerPort
      - 3888:3888 # leaderPort
      - 1233:1233 # JMX Exporter
    environment:
      SERVER_JVMFLAGS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9999 -javaagent:/usr/app/jmx_prometheus_javaagent.jar=1233:/usr/app/prometheus.yml
      JMXPORT: 9999

  kafka:
    image: vg/kafka:latest
    ports:
      - 9092 #TODO назначение
      - 1234:1234 # JMX Exporter
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.1.6 #TODO что должно быть?
      KAFKA_ADVERTISED_PORT: "9092"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #FIXME ошибка при запуске на удаленном docker-хосте:
      #   /usr/bin/start-kafka.sh: line 107: KAFKA_JMX_OPTS=... bad substitution
      # временно убрал
#      KAFKA_JMX_OPTS: -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote.rmi.port=9999 -javaagent:/opt/prometheus/jmx_prometheus_javaagent.jar=1234:/opt/prometheus/prometheus.yml
      KAFKA_JMX_OPTS:
      JMX_PORT: 9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper